### ISSUE TITLE
Metaclass problem

### ISSUE THREAD

**Issue by dparkins** [Samreay/SurveyVisualiser#5]
I get the following error message when I attempt to run 'examples.py'

> Traceback (most recent call last):
  File "examples.py", line 1, in <module>
    from surveyvis.camera import OrbitZoomCamera
  File "/Users/uqdpark7/Projects/SurveyVisualiser/surveyvis/camera.py", line 5
    class Camera(metaclass=ABCMeta):
                          ^
SyntaxError: invalid syntax

**Comment by Samreay** [comment]
I believe this should work using python 3. The metaclass stuff is different
from how python 2 does it
